[package]
name = "network"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.27.2"
egui = "0.27.2"
dns-lookup = "2.0.4"
get_if_addrs = "0.5.3"
serde = { version = "1.0.219", features = ["derive"] }
sysinfo = "0.35.2"
